### ISSUE TITLE
"Failed to initialize" error after latest update

### ISSUE THREAD

**Issue by cbcb00** [penguin-teal/gnome-openweather#10]
Currently running Gnome 45.4 on Bazzite, the extension fails to run after latest update and shows an error message - "Failed to initialize"

**Comment by cbcb00** [comment]
Currently running Gnome 45.4 on Bazzite, the extension fails to run after latest update and shows an error message - "Failed to initialize"

**Comment by penguin-teal** [comment]
Darn it! Thanks for the report; can you still open the extension settings through the extension app and paste in the settings from "About > Copy Settings JSON"?

**Comment by cbcb00** [comment]
Yes, I am able to launch the extension settings. Pasting the info below.

```
{"app-version":"130","git-version":"130.r1.g033c682","gnome-version":"45.4","actual-city":"1","has-run":"true","locs":"[(0, '<NAME>', 0, '<PLACE>')]","show-comment-in-panel":"false","menu-alignment":"60.227272727272727","position-in-panel":"'left'"}
```

**Comment by cbcb00** [comment]
Apologies, I seem to have fixed it by changing the location and map providers. Turned the extension on and off and it works now. Shall I close this report?

**Comment by penguin-teal** [comment]
Leave it open there's still some issue here, it shouldn't've ever failed. The reason it did is because those settings *should* be invalid. It says you have the second location selected, but it also says you only have one location added.
Did you always only have one location, or before the update did you have two?

**Comment by derek-shnosh** [comment]
I am experiencing the same issue.

I have tried adding the location again and then deleting the old entry, as well as disabling/enabling the extension.

```json
{
    "app-version": "130",
    "git-version": "130.r1.g033c682",
    "gnome-version": "45.2",
    "unit": "'fahrenheit'",
    "actual-city": "1",
    "prefs-default-width": "700",
    "translate-condition": "true",
    "has-run": "true",
    "days-forecast": "0",
    "prefs-default-height": "906",
    "city": "'38.8339578,-104.825348>Colorado Springs, Colorado>0'",
    "locs": "[(0, '<NAME>', 0, '<PLACE>')]",
    "my-loc-prov": "'geoclue'",
    "expand-forecast": "false",
    "center-forecast": "true",
    "show-sunsetrise-in-panel": "false",
    "geolocation-provider": "'openstreetmaps'",
    "show-comment-in-forecast": "true",
    "use-system-icons": "true",
    "show-comment-in-panel": "false",
    "position-in-panel": "'center'",
    "wind-speed-unit": "'mph'"
}
```

**Comment by cbcb00** [comment]
> Leave it open there's still some issue here, it shouldn't've ever failed. The reason it did is because those settings _should_ be invalid. It says you have the second location selected, but it also says you only have one location added. Did you always only have one location, or before the update did you have two?

Looks like others are facing too, so leaving it open. I've always had only one location set. Yesterday, I added two locations, deleted one and then cycled providers, after which it worked while restarting the extension.

**Comment by penguin-teal** [comment]
I think f6457b9 or 9fa3038 fixed it, I'll leave it open until it's confirmed.

**Comment by derek-shnosh** [comment]
> @derek-shnosh Settings > General > Reset Settings should fix it if the extension still isn't working for you.

That did sort it out, thanks!
