### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by ironbone** [penguin-teal/gnome-openweather#12]
The application has stopped to work under Gnome 46.
I get the error: this._currentWeather is undefined

**Comment by Neo-29** [comment]
Confirmed

**Comment by MrGamerDoesGames** [comment]
+1

**Comment by washran** [comment]
Also confirmed.

**Comment by Neo-29** [comment]
Someone working on it ,should we consider the project abandonned?

**Comment by MrGamerDoesGames** [comment]
> Someone working on it ,should we consider the project abandonned?

The last commit was 19 days ago, before GNOME 46's release. So yes, unfortunately, this project may be dead.

**Comment by washran** [comment]
I doubt the project is dead. Weather or not is a different project and it works with Gnome 46. Give the maintainer more time to troubleshoot.

**Comment by Neo-29** [comment]
> I doubt the project is dead. Weather or not is a different project and it works with Gnome 46. Give the maintainer more time to troubleshoot.

Does not on g46

**Comment by Neo-29** [comment]
> I doubt the project is dead. Weather or not is a different project and it works with Gnome 46. Give the maintainer more time to troubleshoot.

No reaction from him either

**Comment by BooBerry** [comment]
It's way, way too soon to assume the project is dead. Developers have lives and other priorities too, sometimes it just takes time. It's not like the original OpenWeather project that hasn't seen any updates in many months, one could argue that one is 'dead' but even then it may not be.

Just have patience and let's see what happens. Plus the project is open-source so anyone able could potentially fork it or update it and submit a pull request.

**Comment by penguin-teal** [comment]
Sorry I was busy, I will try to fix this issue as soon as possible. The project is definitely not dead, although I won't be pushing commits super frequently. I have not even booted up a Gnome 46 computer yet.

**Comment by crimist** [comment]
No need to apologize - thanks for your work and forking the project.
Peoples lack of patience with FOSS is always disappointing.

**Comment by crimist** [comment]
I've downgraded back to gnome 45 at the moment but I believe this extension was broken due to the changes around [`Clutter.Actor.add_child`](https://gnome.pages.gitlab.gnome.org/mutter/clutter/method.Actor.add_child.html).

Here's a PR from another project with similar changes required https://github.com/oae/gnome-shell-pano/pull/264.

**Comment by penguin-teal** [comment]
Done!
And I changed some stuff that got deprecated so there is a higher chance that GNOME 47 won't break anything.

**Comment by washran** [comment]
Thanks for fixing it for Gnome 46.
