### ISSUE TITLE
Conditions in panel button are cut off

### ISSUE THREAD

**Issue by Ticklezz** [penguin-teal/gnome-openweather#16]
![Screenshot from 2024-03-30 00-30-11](https://github.com/penguin-teal/gnome-openweather/assets/113319295/7aefc378-584e-4234-a48b-ae6b257de641)
 
The forecast is now hidden, you can scroll over it and it will show as normal. It was not like that before.
![Screenshot from 2024-03-30 00-31-59](https://github.com/penguin-teal/gnome-openweather/assets/113319295/619703fd-da9e-4176-9bf8-6e141bca45dd)

**Comment by penguin-teal** [comment]
Thanks for the bug report.
Are you on GNOME 46 or 45?

**Comment by Ticklezz** [comment]
> Thanks for the bug report. Can you go to Settings > About > Copy Settings JSON and paste it here?

{"app-version":"132","git-version":"131.r18.g8cddeed","gnome-version":"45.2","unit":"'fahrenheit'","actual-city":"0","translate-condition":"true","sun-in-panel-first":"false","has-run":"true","location-text-length":"0","locs":"[(0, '<NAME>', 0, '<PLACE>')]","show-sunsetrise-in-panel":"false","position-index":"0","use-system-icons":"true","pressure-unit":"'mbar'","disable-forecast":"false","clock-format":"'12h'","loc-refresh-interval":"10.0","menu-alignment":"51.136363636363633","position-in-panel":"'center'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}

**Comment by penguin-teal** [comment]
It looks like my update for GNOME 46 broke it for GNOME 45!
I've fixed it with the latest commit; now both GNOME versions work.
