### ISSUE TITLE
bug: Right "Position in panel" looks off

### ISSUE THREAD

**Issue by fiftydinar** [penguin-teal/gnome-openweather#17]
How it looks right now:
![Screenshot from 2024-03-30 16-10-12](https://github.com/penguin-teal/gnome-openweather/assets/65243233/cfe3ac0b-62e8-4c17-aad6-2f292a2a29dd)

How it should look (took from my other repo):
![output](https://github.com/penguin-teal/gnome-openweather/assets/65243233/70ba610d-ffd9-4c60-a55a-cbc7c0f372b1)

This behavior happens since v132 version.

Gnome 45
Fedora Silverblue 39
RPM package

**Comment by penguin-teal** [comment]
Thanks for the bug report.
Are you certain it is not another extension doing that? I also notice that your second screenshot has some text that says "sr" but that text appears to be missing in the first one; if you hover over it does it highlight like there is an additional missing button between the weather button and the network/sound/power buttons?

**Comment by TynInks** [comment]
I am also experiencing this behavior after updating to version 132. The temperature is significantly further away from the other icons than in previous versions. Only seems to affect Right-Aligned position.

Default Behavior, no other extensions:  
![Weather Text Location - Default](https://github.com/penguin-teal/gnome-openweather/assets/159389906/095f2152-34ba-4cd0-b208-c44be5aa7532)

Additionally, sometimes after it refreshes the data, the temperature cuts off:  
![Weather Text Location - Number Cut Off](https://github.com/penguin-teal/gnome-openweather/assets/159389906/4ad8be56-ffa6-4744-bb86-b913a37ad4ea)

I've included my settings, but they're pretty close to the defaults:  
[app version 132 git version.txt](https://github.com/penguin-teal/gnome-openweather/files/14813728/app.version.132.git.version.txt)

**Comment by fiftydinar** [comment]
> Thanks for the bug report. Are you certain it is not another extension doing that? I also notice that your second screenshot has some text that says "sr" but that text appears to be missing in the first one; if you hover over it does it highlight like there is an additional missing button between the weather button and the network/sound/power buttons?

"sr" is the language switcher. I disabled 2nd language so that's why I don't have that.

Tested with no other extensions & factory-reseted the extension to defaults, no change.

**Comment by penguin-teal** [comment]
In trying to fix it for GNOME 46 it broke GNOME 45!
Now both versions work with the new commit.
