### ISSUE TITLE
Forecast in pop-up is blank in GNOME 45

### ISSUE THREAD

**Issue by S0litaire** [penguin-teal/gnome-openweather#18]
I think recent update has broken something in the widget.

The Forecast drop down is empty.

Ubuntu : 23.10
Firefox : 124.0.1

Settings JSON 

```
{"app-version":"132","git-version":"131.r18.g8cddeed","gnome-version":"45.2","appid":"'b4cbc29034cd3db6dea22928c930865b'","use-default-owm-key":"false","actual-city":"0","prefs-default-width":"700","hi-contrast":"'none'","sun-in-panel-first":"true","has-run":"true","days-forecast":"3","refresh-interval-current":"900","location-text-length":"3","prefs-default-height":"960","delay-ext-init":"4","locs":"[(0, '<NAME>', 0, '<PLACE>')]","center-forecast":"false","my-loc-prov":"'ipinfoio'","show-sunsetrise-in-panel":"true","position-index":"4","geolocation-provider":"'openstreetmaps'","show-comment-in-forecast":"true","use-system-icons":"true","simplify-degrees":"false","wind-direction":"true","pressure-unit":"'bar'","disable-forecast":"false","clock-format":"'24h'","menu-alignment":"100.0","position-in-panel":"'center'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}
```
Here is what it looks like on my system:

![Screenshot from 2024-03-31 21-41-26](https://github.com/penguin-teal/gnome-openweather/assets/1823781/0f4348db-1a8c-42ff-80d8-8f2de6fd9b36)

**Comment by mcwall1064** [comment]
Exact same issue...
Fedora 39 
Gnome 45.5
Firefox 124.0.1

**Comment by penguin-teal** [comment]
I assume the issue must be that the update for GNOME 46 broke something on GNOME 45...
Thanks for the report.

**Comment by penguin-teal** [comment]
In trying to fix it for GNOME 46 it broke GNOME 45!
Now both versions work with the new commit.

**Comment by pawel-rh** [comment]
Unfortunately that is still an open issue

{"app-version":"132","git-version":"131.r18.g8cddeed","gnome-version":"45.2","actual-city":"0","translate-condition":"false","sun-in-panel-first":"false","has-run":"true","days-forecast":"5","decimal-places":"1","delay-ext-init":"3","locs":"[(0, '<NAME>', 0, '<PLACE>')]","expand-forecast":"true","show-sunsetrise-in-panel":"false","simplify-degrees":"true","wind-direction":"true","pressure-unit":"'mbar'","disable-forecast":"false","show-text-in-panel":"false","loc-refresh-interval":"1440.0","show-comment-in-panel":"false"}

![image](https://github.com/penguin-teal/gnome-openweather/assets/67366492/7b318e91-da04-453e-bd18-b21b33ca236b)

**Comment by S0litaire** [comment]
just got around to updating and yes it's still blank 
json : 

`{"app-version":"132","git-version":"132.r0.g5c5eac4","gnome-version":"45.2","appid":"'b4cbc29034cd3db6dea22928c930865b'","use-default-owm-key":"false","actual-city":"0","prefs-default-width":"977","hi-contrast":"'white'","has-run":"true","days-forecast":"5","prefs-default-height":"997","locs":"[(0, '<NAME>', 0, '<PLACE>')]","center-forecast":"true","expand-forecast":"true","my-loc-prov":"'ipinfoio'","show-sunsetrise-in-panel":"true","position-index":"1","geolocation-provider":"'openstreetmaps'","show-comment-in-forecast":"true","simplify-degrees":"false","wind-direction":"true","pressure-unit":"'mbar'","disable-forecast":"false","clock-format":"'24h'","menu-alignment":"87.0","position-in-panel":"'center'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}
`

**Comment by penguin-teal** [comment]
@S0litaire @pawel-rh Sorry to clarify the latest development commit fixed it; there has been no release since then (I still want to fix something else before I make another release). When v133 comes out it will ship with the bug fix. (Commit 952dc54 is newer than both of the versions in your guys' `git-version`.)
