### ISSUE TITLE
Cant setup coordinates

### ISSUE THREAD

**Issue by kariif** [penguin-teal/gnome-openweather#2]
When I try to enter my coordinates from openweathermap and try to save it shows an error: ![image](https://github.com/penguin-teal/gnome-openweather/assets/100517803/a001eaba-de3d-4f06-af97-559cf84f56f1)

**Comment by penguin-teal** [comment]
Thanks for the bug report!
I have fixed the issue and it will be in the next release. Assuming you are using GNOME extensions to get this I recommend for now you click "Add" in the location tab and type the coordinates from there, or use the "My Location" feature.
