### ISSUE TITLE
Undefined showing in front of temperature in panel (最新版无法正常获取天气信息)

### ISSUE THREAD

**Issue by XiaoSong2017** [penguin-teal/gnome-openweather#22]
![image](https://github.com/penguin-teal/gnome-openweather/assets/35443773/793c6453-d427-4b08-a88a-6e36ae8b974b)

**Comment by penguin-teal** [comment]
Thanks for the bug report. I am unable to recreate the issue; could you go to your Extension Settings > "About" > "Copy Settings JSON" and paste it here?

Google Translate:
感谢您的错误报告。 我无法重现该问题； 您可以转到“扩展设置”>“关于”>“Copy Settings JSON”并将其粘贴到此处吗？
这是用谷歌翻译写的。

**Comment by hhlp** [comment]
I've instaled both from gnome-extension.app and from the COPR fedora Repo both with the same error:

here is mine, Extension Settings > "About" > "Copy Settings JSON"

```
{"app-version":"134","git-version":"Unknown","gnome-version":"46.1","appid":"'4ed5bbc59e27c1d5d3ed086bb91c93ea'","use-default-owm-key":"false","actual-city":"0","sun-in-panel-first":"true","has-run":"true","days-forecast":"5","locs":"[(0, '<NAME>', 0, '<PLACE>')]","owm-api-translate":"true","expand-forecast":"true","show-sunsetrise-in-panel":"true","simplify-degrees":"true","wind-direction":"true","menu-alignment":"71.0","position-in-panel":"'center'","show-comment-in-panel":"true"}
```

Regards.,

**Comment by penguin-teal** [comment]
I still can't replicate it, I wonder if this is something to do with localization when converting a number to a string.
@hhlp what is your language set as?

**Comment by hhlp** [comment]
> I still can't replicate it, I wonder if this is something to do with localization when converting a number to a string. @hhlp what is your language set as?

@penguin-teal 

```
hhlp in 🛖  
🕙 20:09:21 ✖  locale
LANG=es_ES.UTF-8
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=
```

Regards.,

**Comment by penguin-teal** [comment]
@hhlp thanks so much, I'll try checking out the extension in Spanish soon.

**Comment by XiaoSong2017** [comment]
> Thanks for the bug report. I am unable to recreate the issue; could you go to your Extension Settings > "About" > "Copy Settings JSON" and paste it here?
> 
> Google Translate: 感谢您的错误报告。 我无法重现该问题； 您可以转到“扩展设置”>“关于”>“Copy Settings JSON”并将其粘贴到此处吗？ 这是用谷歌翻译写的。

{"app-version":"134","git-version":"134.r0.gf2d739e","gnome-version":"45.3","use-default-owm-key":"true","actual-city":"0","hi-contrast":"'white'","sun-in-panel-first":"true","has-run":"true","days-forecast":"3","refresh-interval-current":"600","decimal-places":"2","delay-ext-init":"0","locs":"[(0, '', 1, '')]","owm-api-translate":"true","my-loc-prov":"'ipinfoio'","pressure-decimal-places":"2","speed-decimal-places":"2","show-sunsetrise-in-panel":"true","position-index":"4","geolocation-provider":"'mapquest'","use-system-icons":"false","simplify-degrees":"true","wind-direction":"true","pressure-unit":"'mbar'","disable-forecast":"false","show-text-in-panel":"true","clock-format":"'system'","loc-refresh-interval":"10.0","position-in-panel":"'left'","show-comment-in-panel":"true"}

**Comment by penguin-teal** [comment]
I was unable to ever replicate the behavior, even with my locale set as all Spanish. Does the current update 135 still cause this issue? There was a partial rewrite that could have fixed this, but I was unable to replicate the issue before or after the rewrite.

**Comment by hhlp** [comment]
@penguin-teal 

```
gnome-shell-extension-openweatherrefined-135-1.fc40.noarch
```

Did you tried install a VM with Fedora 39 upgrade via command line to 40 -> https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-offline/, don't touch anything just Install the extension, look if works and next do `sudo dnf upgrade`  and look again...

Regards.,

**Comment by penguin-teal** [comment]
Apparently the issue didn't exist in Arch or Manajro, but did in Fedora! I tried it with v134 and I had the issue, but did not have the issue in v135 so it must have been fixed.
