### ISSUE TITLE
Condition is "undefined" and today's forecast is broken for the last 3 boxes

### ISSUE THREAD

**Issue by kouros1741** [penguin-teal/gnome-openweather#23]
After the last update (134) in manjaro and default theme  I cant see the temprature of next hours and days

![Στιγμιότυπο οθόνης από 2024-04-20 09-34-43](https://github.com/penguin-teal/gnome-openweather/assets/167604830/aedf254e-d91b-47ce-844a-7fef067199e4)
![Στιγμιότυπο οθόνης από 2024-04-20 09-35-08](https://github.com/penguin-teal/gnome-openweather/assets/167604830/3c285c47-8d61-4dc8-92e6-4438a7a25fac)

**Comment by kouros1741** [comment]
{"app-version":"134","git-version":"134.r0.gf2d739e","gnome-version":"46.1","use-default-owm-key":"true","actual-city":"0","weather-provider":"'default'","hi-contrast":"'white'","has-run":"true","days-forecast":"3","locs":"[(0, '<NAME>', 0, '<PLACE>')]","owm-api-translate":"true","expand-forecast":"false","weatherapidotcom-key":"'3a9ea1d56e424165a04232918242004'","show-sunsetrise-in-panel":"false","position-index":"1","use-system-icons":"true","use-default-weatherapidotcom-key":"false","pressure-unit":"'mbar'","disable-forecast":"false","menu-alignment":"50.54545454545454","position-in-panel":"'center'","show-comment-in-panel":"false"}

**Comment by ironbone** [comment]
The problem appear when using OpenWeatherMap. When using WeatherAPI it looks ok

**Comment by kouros1741** [comment]
I confirm that WeatherAPI works.

**Comment by Thorazin** [comment]
I am also having this problem, would you like my JSON file also?

**Comment by penguin-teal** [comment]
I believe this issue may actually be a rate limiting issue and the app keeps getting temporarily blocked. I'm thinking of a solution.

**Comment by penguin-teal** [comment]
My solution to this is to by default choose a random provider every time you boot up your computer (this can be changed by changing Weather Provider from Default). That way there should be a more even distribution between WeatherAPI.com and OpenWeatherMap, and I will probably add more providers.
