### ISSUE TITLE
Forecast time zone seems wrong

### ISSUE THREAD

**Issue by adequacy1** [penguin-teal/gnome-openweather#26]
At 7am, the weather forecast is displayed in the top row starting at 12 noon. Given the three-hour interval, it should start from 9am. Perhaps the time zone difference is not taken into account? Mine is GMT+3.
![Снимок экрана от 2024-04-30 07-22-53](https://github.com/penguin-teal/gnome-openweather/assets/132190843/faed93f2-edf5-4d0a-b98b-55104d2882a8)

**Comment by penguin-teal** [comment]
Thanks for the bug report!
