### ISSUE TITLE
Contrast too low

### ISSUE THREAD

**Issue by rthrejheytjyrtj545** [penguin-teal/gnome-openweather#3]
The high contrast option only works for a small number of elements and requires manual selection for light or dark mode, which is not suitable for automatic theme changing situations where the text may become completely unreadable

Such a gray is difficult to read even with a custom black background, it is not entirely clear why not use the default text color

**Comment by penguin-teal** [comment]
Thanks for reporting the issue!
The color is determined by your shell theming, not the extension.
A issue for high contrast was started on an old fork of the project, where Jason Oickle said it was determined by the shell and not able to be overridden, and he refused to add the feature. I have added the feature as a "hack."
I can make it affect all the text, however I can't adjust for "automatic theme changing situations" and I can only program in constant colors as far as I know.

**Comment by penguin-teal** [comment]
Fixed, will be shipped with v128 soon.
