### ISSUE TITLE
Added and fixed some translations.

### ISSUE THREAD

**Issue by federicolencina** [penguin-teal/gnome-openweather#37]
## Current and Correction

Key Correction:
In Spanish we use the word 'Tiempo' as the English word 'Time', for refer to Weather condition instead of the word 'Clima'.
Added some missing translations --**Compare** at: 
https://github.com/penguin-teal/gnome-openweather/compare/master...federicolencina:federicolencina-patch-1-1?expand=1

Greetings.
Fede.
##

**Comment by penguin-teal** [comment]
Merged #38.
Thanks!
