### ISSUE TITLE
No weather.

### ISSUE THREAD

**Issue by Ticklezz** [penguin-teal/gnome-openweather#39]
## Description

Describe the bug.
No weather at all now. Even using own API or stock API. 
![Screenshot from 2024-06-11 03-39-41](https://github.com/penguin-teal/gnome-openweather/assets/113319295/2b136367-b958-499d-b37d-22d91f76d288)

## System

Which Linux distro are you using?
Ubuntu
## Settings

```json
Go to extension settings > "About" > "Copy Settings JSON" and paste here.
```
{"app-version":"136","git-version":"136.r1.g8d02397","gnome-version":"46.0","user-locale":"en","unit":"'fahrenheit'","appid":"<KEY>","actual-city":"1","weather-provider":"'weatherapicom'","has-run":"true","locs":"[(1, '', 1, ''), (0, '<NAME>', 0, '<PLACE>')]","last-init-error":"'(2024/05/11) TypeError: settings.set_value is not a function'","my-loc-prov":"'ipinfoio'","weatherapidotcom-key":"<KEY>","simplify-degrees":"true","geolocation-provider":"'openstreetmaps'","pressure-unit":"'inHg'","clock-format":"'12h'","position-in-panel":"'center'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}

**Comment by Ticklezz** [comment]
Another restart and entering API key again and weather appeared.

**Comment by penguin-teal** [comment]
Yeah, entering the key again will have fixed it. This happened because of a format change and your settings should have been migrated but it appears that this is bugged (see #40).
Thanks for the report!
