### ISSUE TITLE
Release as an .RPM for Fedora Silverblue

### ISSUE THREAD

**Issue by tsilvs** [penguin-teal/gnome-openweather#4]
On immutable root distros software could be installed system-wide only in variable directories or layered as proper packages via package manager.

For example, in Fedora Silverblue 39 (which I'm using), system extension directory `/usr/share/gnome-shell/extensions/` is located within a read-only file system.

Examples of GNOME Extensions that are present in Fedora repos:

* `just-perfection-desktop@just-perfection`
* `caffeine@patapon.info`
* `dash-to-dock@micxgx.gmail.com`
* `forge@jmmaranan.com`
* `pomodoro@arun.codito.in`
* `gsconnect@andyholmes.github.io`

**Comment by penguin-teal** [comment]
I will try to work on making Arch, Debian, and Fedora packages after I finish up v128.

**Comment by fiftydinar** [comment]
I use OpenWeather extension in my custom image based on Universal Blue, so I have an interest in making RPM to host on COPR.

**Comment by fiftydinar** [comment]
Here, I built RPM in COPR for this extension:

https://copr.fedorainfracloud.org/coprs/fiftydinar/gnome-shell-extension-openweatherrefined/

I set-up notifications when new release happens, so that's when I'm going to update it.

**Comment by penguin-teal** [comment]
Thanks so much @fiftydinar! I had looked into making an RPM package and tried a bunch but hit some hiccups and didn't pursue it much farther.
I'll close this issue; I might make an AUR package at some point too.

**Comment by tsilvs** [comment]
@fiftydinar thank you! Testing it now.
