### ISSUE TITLE
Can't use custom API key for OpenWeatherMap

### ISSUE THREAD

**Issue by abdullahsabbir** [penguin-teal/gnome-openweather#41]
## Description

Personal API key for OpenWeatherMap is not working with the extension. After enabling "use custom API Key" and pasting the API code from OpenWeatherMap in the extension settings and closing the extension settings window simply reset the "Use Custom API Key" checkbox back to disabled and use the extension's own API key.

## System

Arch Linux with Gnome 46.2, Linux 6.9.4

## Settings

```json
{"app-version":"136","git-version":"136.r1.g8d02397","gnome-version":"46.2","user-locale":"en","appid":"<KEY>","actual-city":"0","weather-provider":"'openweathermap'","has-run":"true","delay-ext-init":"0","locs":"[(0, '<NAME>', 0, '<PLACE>')]","owm-api-translate":"false","show-sunsetrise-in-panel":"false","last-init-error":"\"'(2024/05/11) TypeError: settings.set_value is not a function'\"","frozen":"false","weatherapidotcom-key":"<KEY>","position-index":"1","pressure-unit":"'mbar'","menu-alignment":"40.909090909090914","position-in-panel":"'center'","show-comment-in-panel":"false"}
```

**Comment by penguin-teal** [comment]
Thanks for the bug report! It'll be fixed in the next release which will ship soon.
