### ISSUE TITLE
Add Open-Meteo as Weather Provider

### ISSUE THREAD

**Issue by bbourcy** [penguin-teal/gnome-openweather#45]
Hello! Love the extension, thanks for your work in maintaining this. 

I have noticed the issues others have reported due to rate limits. I understand that you can provide a personal API Key, but I would also propose adding [Open-Meteo](https://open-meteo.com/) as a Weather Provider to additionally increase capacity and flexibility of the tool.

The API is open-source and free for non-commercial use under 10,000 requests per day. No API key is required to retrieve data. Curious to know if you feel this would be a material benefit for the extension.

Thanks

**Comment by penguin-teal** [comment]
Funny enough if you check the last commit (from yesterday) b11628a30a54f3d1e0c7fef064ef97dbd43a300d it's already in progress.
This might become the default in the future however I'd probably roll it out as just part of the "Adaptive" thing to see if it works. It will probably be out in the next update and in the future will hopefully be the default if it seems to go well.

**Comment by bbourcy** [comment]
Ah! I see that now, very funny timing. 

Cool to hear that you have already considered this and an implementation is in progress. Have had good experiences with Open-Meteo myself so interested to see how things shake out in the future. I'll close this out.
