### ISSUE TITLE
Launches, but drop down stopped working

### ISSUE THREAD

**Issue by joekm** [penguin-teal/gnome-openweather#5]
Got this yesterday from the Gnome Extensions site and it seemed to be working fine.  So, I uninstalled the old version by toppk I got directly from git.  This morning, it will launch but the drop down doesn't work at all.

**Comment by penguin-teal** [comment]
Thanks for the bug report joekm,
I'm not sure what could've caused that. Does the panel show a temperature, or just "..." with a refresh arrow? Also, will the preferences window open if you open it from the "Extensions" GNOME app?
Also, to make sure, you downloaded from the GNOME Extension site and not this GitHub repo right?

**Comment by penguin-teal** [comment]
Thanks for the bug report,
I've been able to reproduce the behavior and I don't believe it is related to Toppk's extension. If the extension starts when your PC has no Internet, it fails to start. I will fix this for v128.
Would you wanna try going to the extensions app, disabling, and re-enabling (make sure you currently have Internet) and verify it then works?

**Comment by joekm** [comment]
Disabling and re-enabling has no impact.  The computer I'm running is my desktop PC that connected via ethernet cable so, internet starts right away.  On the other hand, I do run firewalld, which takes a couple seconds to start and I also have NVMe memory so my computer goes from GDM to desktop really fast.

I was wondering if deleting the old version (toppk) impacted a configuration file your version needed, was going to try removing and re-installing.   I'll hold off for now though.

**Comment by matteopaolucci** [comment]
> Disabling and re-enabling has no impact. The computer I'm running is my desktop PC that connected via ethernet cable so, internet starts right away. On the other hand, I do run firewalld, which takes a couple seconds to start and I also have NVMe memory so my computer goes from GDM to desktop really fast.
> 
> I was wondering if deleting the old version (toppk) impacted a configuration file your version needed, was going to try removing and re-installing. I'll hold off for now though.

Same problem here. After installation it worked fine, now after one reboot the drop-down menu isn't working. I have already tried to disable and re-enable the extension, but it doesn't work.

**Comment by penguin-teal** [comment]
@joekm @matteopaolucci Can you verify you are using the GNOME Extensions Website version and _not_ the version currently on GitHub (the latest git version is not stable).
If so can you open the "Settings" window via GNOME Extension app?
Also does the extension show a temperature in the panel or just "..."?
Sorry for all the questions but I haven't been able to reproduce the issue with an Internet connection on either my NVMe laptop or my hardrive desktop (although both use Wi-Fi).

**Comment by joekm** [comment]
Yes, I used the Gnome extensions website.  Looking through the settings, I
did notice I was getting an error message regarding the lat, long
coordinates.  I get this message even if I use the cords provided by your
extension.

**Comment by joekm** [comment]
Yes, I see the temperature and icon in the picture.  Screen grab posted.
![image](https://github.com/penguin-teal/gnome-openweather/assets/4186241/35cd8b8c-6c1e-45eb-8b39-5baebbe3e728)

**Comment by joekm** [comment]
Looks to be working, thanks :)

**Comment by penguin-teal** [comment]
Thanks, I'm glad it got fixed!

**Comment by joekm** [comment]
Alas, the problem has returned.  Shows weather but drop down is not working.

**Comment by jimibananas** [comment]
Hello - I am having the same problem.  Drop down is not working.  I am running Solus 4.5 Gnome and this seemed to start for me after the weekly updates applied on Friday Feb 09.  Thank you.

**Comment by penguin-teal** [comment]
I am going to release an update soon (I've been busy) that'll have a place where you can copy your preferences as JSON onto your clipboard, and I'll try to use that to diagnose the issue since I still haven't been able to recreate it on multiple devices.

**Comment by washran** [comment]
I was able to view dropdown on Manjaro with Gnome 45.2 when I updated to gnome 45.3 the dropdown stopped working. When you hover over the weather top bar, it highlights, that's all. Not sure I'm explaining the bug right?

**Comment by jimibananas** [comment]
Yes, that is exactly the same as what I am experiencing.  I also have Gnome 45.3 which Solus must have pushed last Friday because it worked fine before that.  Thanks for looking into this.  I love the extension.

**Comment by penguin-teal** [comment]
Thanks for your guys' comments, that is very useful. Both my machines I've tested on are GNOME 45.4, so this might be a GNOME 45.3 issue (not sure why it'd be, but it's a lead!). When I have time I will use a VM and try it from there, however I am still very busy so I apologize it'll probably take up to a week to fix. (Also if anyone sees who is willing to I am definitely open to pull requests!)

**Comment by jimibananas** [comment]
Thank you! I might be able to set up a test machine for this in a week or so for pull requests.  I'll let you know.

**Comment by washran** [comment]
> Thanks for your guys' comments, that is very useful. Both my machines I've tested on are GNOME 45.4, so this might be a GNOME 45.3 issue (not sure why it'd be, but it's a lead!). When I have time I will use a VM and try it from there, however I am still very busy so I apologize it'll probably take up to a week to fix. (Also if anyone sees who is willing to I am definitely open to pull requests!)

I updated gnome to 45.4. Openweather is working as intended.

**Comment by penguin-teal** [comment]
I think v129 fixes this. If you are running v129 (go to extension settings > About > OpenWeather Refined Version) and it still does not work go to About > Copy Settings JSON and click "Copy" and paste it here.

**Comment by jimibananas** [comment]
Hi... In Fedora 39 v128 is working great.  Under Solus it still doesn't work.  Solus is an independent distro and not based on Debian, Arch, etc. so I think something happened to one of the dependencies during one of the weekly updates.  Installing from GNOME Extensions installs v128.  Will you be updating that to make v129 available under shell version 45?  I can try installing v129 from source. Will the git pull 128 or 129?  I can try it but I think the problem might be Solus now.

**Comment by penguin-teal** [comment]
Hi @jimibananas, thanks for the comment. If you wait a few days it will come out on GNOME Extensions; there is one guy who has to manually review every update I post on there! The version on GitHub right now *is* v129, so if you want to manually install from here then this would be the latest version, however it might just be easier to wait for GNOME Extensions to release the update.

**Comment by washran** [comment]
I installed v129 and can confirm it works. I used your git repo. @penguin-teal thumbs up.

**Comment by jimibananas** [comment]
Hi @penguin-teal - Thank you for looking at this!  I'll wait for the update to arrive on GNOME Extensions.

**Comment by joekm** [comment]
Yup, I split my time between Gnome and Hyprland but, it's definitely working and has been for a bit now.  Thanks keeping the best weather app on Linux alive :)
