### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by lev741** [penguin-teal/gnome-openweather#61]
## Description
Not translatable strings:
Section Locations/Provider don`t have strings to translate exept string "Geolocation Provider"

All translated forecast expressions (like Storm) are comented now and not used for OpenWeatherMap. So can`t be translated now and are on english forecast expressions only. Not czech. 
Is it end of translation of forecast expressions?

## My Version 
138.0.g6367a11 with the latest [openweather.pot](https://github.com/penguin-teal/gnome-openweather/blob/master/po/openweather.pot)

**Comment by penguin-teal** [comment]
I believe the issue is now because of the way the code is written it cannot auto-generate the translation keys. I think the solution will be to just write a shell script to extract the necessary keys and throw it in the Makefile. Will fix soon.

**Comment by penguin-teal** [comment]
Ended up essentially using a no-op function to denote that that string will be eventually passed to gettext and there is a special `--keyword` option in `xgettext` for that.
All weather conditions should appear in the `.pot` now.
