### ISSUE TITLE
Openweather Revisited Fails with Too Many Users

### ISSUE THREAD

**Issue by kmand** [penguin-teal/gnome-openweather#66]
## Description

This extension has started to fail continuously with "Provider Openweather Map has Too Many Users". This even though opening openweather map in  the browser works fine.

## System

Ubuntu 24.05

## Settings

```
{"app-version":"138","git-version":"138.r0.g6367a11","gnome-version":"46.0","user-locale":"en","unit":"'fahrenheit'","custom-keys":["","",""],"appid":"<REDACTED>","actual-city":"2","weather-provider":"'openweathermap'","has-run":"true","locs":[{},{},{}],"my-loc-prov":"'ipinfoio'","weatherapidotcom-key":"<REDACTED>","geolocation-appid-mapquest":"<REDACTED>","pressure-unit":"'inHg'","position-in-panel":"'center'","wind-speed-unit":"'mph'"}

**Comment by penguin-teal** [comment]
Thanks for the report, but this isn't a bug (see [OpenWeather Refined Custom API Keys](https://penguin-teal.github.io/openweather/custom-keys/)); see #67 for the change being worked on.
