### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by jaovr** [penguin-teal/gnome-openweather#71]
Hello,

I’ve noticed that the extension has not been functioning correctly for the past 1-2 weeks. The popup window and top bar remain empty, and I’ve also encountered API issues, such as "cannot connect to provider" or "provider has a lot of users." I also tried switching to another provider, but that didn’t resolve the issue. For reference, I am using the Ubuntu 22.04 distribution.

![Screenshot from 2024-07-31 13-57-51](https://github.com/user-attachments/assets/749e3e9a-818d-4206-87ea-11c677a87853)

![Screenshot from 2024-07-31 13-58-27](https://github.com/user-attachments/assets/8a301c92-8bef-4b72-ac74-761246446724)

**Comment by penguin-teal** [comment]
This is because of too many calls to the servers for the month (which is why it didn't work end of July but then worked August 1st) --- a change to this is coming soon.
