### ISSUE TITLE
wrong icons with provider visualcrossing

### ISSUE THREAD

**Issue by MarkyMarkDE** [penguin-teal/gnome-openweather#79]
we have the wrong weather icon, when you are using visualcrossing.com as provider.
On openwaethermap.org all is perfect but at the same time with same weather conditions the icon is complete different.
Example: 23 Uhr (11pm) we have clear sky and
- visualcrossing shows sunny - sunny at 11pm?
- Openweathermap shows the correct moon icon with clear sky

The used icon-set didn't change anything.

visualcrossing.com
![vc](https://github.com/user-attachments/assets/1b0bd875-e17f-42e5-9597-196fbd6e5922)

openweathermap.org
![owm](https://github.com/user-attachments/assets/a95a2d2b-45b5-4151-a16b-ace79dfe88aa)

**Comment by penguin-teal** [comment]
Thanks for the bug report, I'll look into it.

**Comment by penguin-teal** [comment]
This was fixed by #73 (commit 0754ed6f4a9c2492192b64aa5a6771b3f6c29367) and will be fixed in the next release.

**Comment by MarkyMarkDE** [comment]
> This was fixed by #73 (commit [0754ed6](https://github.com/penguin-teal/gnome-openweather/commit/0754ed6f4a9c2492192b64aa5a6771b3f6c29367)) and will be fixed in the next release.

Thank you really much for all.
