### ISSUE TITLE
Changing the location

### ISSUE THREAD

**Issue by ironbone** [penguin-teal/gnome-openweather#8]
When having multiple locations, it is not possible to select them from the list and to choose the other.

**Comment by penguin-teal** [comment]
Hello, thanks for your bug report. I am unable to replicate the issue, can you go to Settings > About > Copy Settings JSON and paste it in here so I can see your settings?

**Comment by penguin-teal** [comment]
I thought you were referring to the settings menu but I recreated the issue with the dropdown in the panel and fixed it.
